### ISSUE TITLE
输入我的邀请码 2365QG 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by cnwxi** [YoulianBoshi/lantern-vpn#11]
输入我的邀请码 2365QG 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stevenwsg** [comment]
你好！ 这个是必须购买一年的时长才能获得三个月嘛？

**Comment by tomatoKnightJ** [comment]
输入我的邀请码 YPBKSVV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
