### ISSUE TITLE
socks5代理无效

### ISSUE THREAD

**Issue by gankang** [YoulianBoshi/lantern-vpn#43]
![手心输入法截图20200715211051702](https://user-images.githubusercontent.com/62201630/87549012-d6161700-c6df-11ea-97e6-f435d5ed58a5.jpg)
![手心输入法截图20200715211114703](https://user-images.githubusercontent.com/62201630/87549021-d9110780-c6df-11ea-8fd0-d7f272035b4c.jpg)

设置如上图，访问不了google.com.hk。求解。

**Comment by YoulianBoshi** [comment]
蓝灯每一次启动端口都不同

**Comment by gankang** [comment]
每次启动端口都一样，http代理没问题，SOCKS还是不行。
![image](https://user-images.githubusercontent.com/62201630/87750226-73cb2c80-c82d-11ea-8d18-8461f6930a01.png)
